version: '3'

services:

  database:
    image: mariadb
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: sd
  
  sd-backend:
    image: jtr860830/sd-backend
    depends_on:
      - database
    restart: always
    environment:
      DBMS: mysql
      DBLC: root:password@tcp(database:3306)/sd?charset=utf8&parseTime=True&loc=Local
    ports:
      - "8080:8080"
