apiVersion: v1
kind: Pod
metadata: 
  name: sd-database
  labels:
    app: sd-database
spec:
  containers:
  - name: sd-database
    image: mariadb
    ports: 
    - name: sd-db-port
      containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_DATABASE
      value: sd
